server:
  port: 8880

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#    instance:
#      preferIpAddress: true
#    healthcheck:
#      enabled: true
    region: eu-central-1
